name: Code Style

on:
  pull_request:
    paths:
      - 'wifi-connect'
  push:
    paths:
      - 'wifi-connect'
      
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check for leftover println
        run: cd wifi-connect && ./tests/left_over_println.sh
      - name: Check formatting
        run: cd wifi-connect && cargo fmt --all -- --check
